### ISSUE TITLE
Map resolution

### ISSUE THREAD

**Issue by HukamiEstia** [weigert/SimpleHydrology#11]
Hello,

I browsed through the code but couldn't identify a point where the map resolution is defined, is there any ? How did you choose your simulation parameters ?

Thank you

**Comment by weigert** [comment]
The map resolution can be found here: https://github.com/weigert/SimpleHydrology/blob/master/source/cellpool.h#L167

The reason the map resolution is there, is because I rewrote the map to support non-square maps, thus splitting the world into tiles. This is for future parallelization schemes. If you want to double the world size, I recommend changing the value of mapsize to 2. You can then run the simulation at a "coarser" resolution by setting lodsize to 2 (or any power of two).

Sorry that this is not explained anywhere, these features are experimental and I am cleaning them up.

You can also alter the physical height-scale here too (has a large effect on the result).

Note that changing this value actually increases the "physical" size of the map, not just the resolution. This means that increasing the value will make the map BIGGER, not more detailed, and the erosion code WILL run slower on a larger map (because of particle lifetimes, among other things).

I chose the simulation parameters by de-dimensionalization of the physics and then tuning the dimensionless parameters. This was done to reduce parameter complexity. Results approximate slices of the true physical parameter space.

The current version of the code is difficult to configure without having to recompile. Sorry about that.

**Comment by weigert** [comment]
For a much reduced version of the code, without graphical interface, but with full data export, check out the `tools` branch of this repository: https://github.com/erosiv/soillib

This is much easier to read and understand.

This is where I am currently unifying all the concepts.

**Comment by HukamiEstia** [comment]
I see! It seemed like you made it adimensional but I wasn't sure thank you. 
Cool project btw !
