### ISSUE TITLE
build troubles

### ISSUE THREAD

**Issue by BMaxV** [weigert/SimpleHydrology#13]
Hi there!

Sorry to bother you, I'm assuming this is more on me, since it's a short list of build instructions and I'm very experienced with C things.

I'm assuming with glm you meant https://github.com/g-truc/glm and I did successfully build your tinyengine. But when I try to run the make all for this project, I get this error:

```
g++-10 -std=c++20 -ggdb3 SimpleHydrology.cpp -Wfatal-errors -O2 -I/home/max/.local/include -L/home/max/.local/lib -lTinyEngine -lX11 -lpthread -lSDL2 -lSDL2_image -lSDL2_mixer -lSDL2_ttf -lGL -lGLEW -lboost_system -lboost_filesystem -o hydrology
make: g++-10: No such file or directory
make: *** [Makefile:8: all] Error 127
```

If it's a short make list, maybe it's an easy fix for me?

Cool project! Thanks for open sourcing! 

If I can't make it work, I will figure out something else, but this is certainly a great inspiration.

**Comment by weigert** [comment]
Hi @BMaxV. `g++-10` is just a name for the `g++` executable that you should have installed to enable compiling with `c++20`. It must be that on your platform, the compiler is named differently. I believe it is (or was) called `g++-10` on some version of ubuntu or fedora to enable compiling with the 20 standard.

The fix is simple: depending on your platform, find out what the g++ version / executable is that supports the 20 standard. Then replace `g++-10` with that version of `g++`. Maybe it's just called `g++`. You can check what is is called in your successful tinyengine build!

**Comment by BMaxV** [comment]
That worked, thank you! Very cool project! 

I'm not sure how to apply the output. It doesn't produce a finished image? I don't know if you meant to open source it as a tool for other people to use.

Anyway, the build works, and "the inclined and skilled reader" could definitely make use of it.
